Script started on Sat 10 Dec 2016 04:36:54 AM EST
[?1034hbash-4.1$ sys161 kernel
sys161: System/161 release 1.14, compiled Sep  4 2014 10:34:58

OS/161 base system version 1.11
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Philip and Prasad's system version 0 (ASST3 #41)

Cpu is MIPS r2000/r3000
316k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

 OS/161 kernel [? for menu]: p testbin/matmult
matmult finished.
answer is: 8772192 (should be 8772192)
Passed.
O
bash-4.1$ exit
exit

Script done on Sat 10 Dec 2016 04:37:43 AM EST
